apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-app
  namespace: PLACEHOLDER_NAMESPACE
  labels:
    app: user-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-app
  template:
    metadata:
      labels:
        app: user-app
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values: 
                  - user-app
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: user-app
        image: PLACEHOLDER_CONTAINER_REGISTRY/PLACEHOLDER_IMAGE_REPOSITORY:PLACEHOLDER_TAG
        ports:
        - containerPort: 8082
        resources:
          requests:
            cpu: "50m"
            memory: "256Mi"
          limits:
            cpu: "100m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8082
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet: 
            path: /health/ready
            port: 8082
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:8082"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: ProducerSettings__Host
          value: rabbitmq-service
        - name: ConnectionStrings__DefaultConnection
          valueFrom:
            secretKeyRef:
              name: db-connection-user
              key: ConnectionStrings__DefaultConnection
        - name: ConnectionStrings__DatabaseDllConnection
          valueFrom:
            secretKeyRef:
              name: db-connection-user
              key: ConnectionStrings__DatabaseDllConnection
---
apiVersion: v1
kind: Service
metadata:
  name: user-app-service
  namespace: PLACEHOLDER_NAMESPACE
spec:
  selector:
    app: user-app
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 8082
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-app-hpa
  namespace: PLACEHOLDER_NAMESPACE
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-app
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 30